spring:
  datasource:
      url:jdbc:h2:mem:spotmusic
          username:sa
          password:null
          driverClassName:org.h2.Driver
  jpa:
      hibernate:
            ddl-auto: create-drop
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
            database-platform: org.hibernate.dialect.H2Dialect
            show-sql: true
  h2:
    console:
      enabled: true

degub: true

